apiVersion: apps/v1
kind: Deployment
metadata:
  name: db1-deployment
  labels:
    app: db1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db1
  template:
    metadata:
     labels:
       app: db1
    spec:
      containers:
        - name: db1
          image: db1-image
          imagePullPolicy: Never
          ports:
            - containerPort: 5000