apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bot-ingress
  annotations:
    kubernetes.io/ingress.class: "telegram-bot"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: "Prefix"
            backend:
              service:
                name: bot-service
                port:
                  number: 80