apiVersion: apps/v1
kind: Deployment
metadata:
  name: db2-deployment
  labels:
    app: db2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db2
  template:
    metadata:
     labels:
       app: db2
    spec:
      initContainers:
        - name: run-migrations
          image: db2-migrations:0.1
          command: ["migrate", "-path", "/migrations", "-database",  "$(SQLITE_DB_PATH)", "up"]
          env:
            - name: SQLITE_DB_PATH
              value: "/flowers.db"
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      containers:
        - name: db2
          image: db2-image
          imagePullPolicy: Never
          ports:
            - containerPort: 8080