apiVersion: apps/v1
kind: Deployment
metadata:
  name: db2-deployment
  labels:
    app: db2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db2
  template:
    metadata:
     labels:
       app: db2
    spec:
      initContainers:
        - name: run-migrations
          image: phillidelli/db2-migrations
          command: ["migrate", "-path", "/migrations", "-database",  "$(POSTGRESQL_URL)"]
          env:
            - name: POSTGRESQL_URL
              value: "postgres://demo:demo@postgres:5432/demo?sslmode=disable"
      containers:
        - name: db2
          image: db2-image
          imagePullPolicy: Never
          ports:
            - containerPort: 8080